CREATE SCHEMA EXAMPLE;

CREATE OR REPLACE TABLE FLAT (
	PROD_NAME VARCHAR(300),
	PROD_PRICE DECIMAL(19,2),
	PROD_DESC VARCHAR(300),
	SUPP_NAME VARCHAR(300),
	SUPP_ADD VARCHAR(300),
	ORDER_NAME VARCHAR(300),
	ORDER_SIZE DECIMAL(19,2),
	ORDER_DATE DATE,
	ORDER_WEIGHT DECIMAL(19,2)
);

INSERT INTO FLAT (
	SELECT 
		'PRODUCTNAME_' || CAST(RAND(1,100) AS DECIMAL(10,0)),
		ROUND(RAND(1, 200), 2),
		'RAND_DESCRIPTION',
		'SUPPLIERNAME_' || CAST(RAND(1,9) AS DECIMAL(10,0)),
		'SUP_ADDRESS',
		'ORDER_NAME_' || CAST(RAND(1,500) AS DECIMAL(10,0)),
		CAST(ROUND(RAND(1, 50), 0) AS DECIMAL(10,0)),
		SYSDATE - ROUND(RAND(1, 365), 0),
		ROUND(RAND(1, 50), 2)
	FROM 
		DUAL 
	CONNECT BY LEVEL <= 100000
);

EXECUTE SCRIPT CONVERT_TO_STAR_SCHEMA('EXAMPLE.FLAT', 'FACT_TABLE', FALSE, FALSE,

	ARRAY(
		'DIMPRODUCT',
		'DIMSUPPLIER',
		'DIMORDER'
	),
	
	ARRAY(
		'1|PROD_NAME',
		'1|PROD_DESC',
		'2|SUPP_NAME',
		'2|SUPP_ADD',
		'3|ORDER_NAME'
	)
);